# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund_transfer', '0004_auto_20161116_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payee',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
